### ISSUE TITLE
only show dates (not time)

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#14]
![image](https://user-images.githubusercontent.com/6021844/30000747-0efd3b7c-9077-11e7-8015-c3717b792440.png)

in all objects

**Comment by xmonader** [comment]
Fixed in https://github.com/Incubaid/crm/commit/83909069e1e7bb09bcc52e876a37959b8df3ba05

![screenshot_2017-09-03_09-24-36](https://user-images.githubusercontent.com/64129/30001289-1ed298a6-9092-11e7-968b-96b619a6f03e.png)

Isn't time done supposed to be used to track how much time was spent with executed on a certain task? if not please clarify

**Comment by despiegk** [comment]
not to do with tracking, time done = in hours (int)
eta is just a date where the person expects this task to be done

**Comment by despiegk** [comment]
see model change

**Comment by xmonader** [comment]
I'll fix that
